"""
generator/image_card.py
───────────────────────
Creates a shareable portrait image card for the Daily Astrology Bot.

What this file does:
  - Downloads the spiritual background image generated by Gemini
  - Overlays the full AI-generated panchang post content (Hinglish) on the card
  - Saves the result to cards/astrology_card_YYYYMMDD.jpg

Card format: 1080px wide, auto-height (grows to fit full content).
Suitable for WhatsApp, Instagram Stories, and Facebook Stories.

This is a SEPARATE feature — it does NOT replace the Telegram text post.

Design principles:
  - Top: Date strip with weekday + date
  - Spiritual background image (context-matched to today's tithi)
  - Deep midnight-blue panel below image for high text readability
  - Section headings via decorative diamond marker (◆) — no emoji dependency
  - Bullet points preserved; labeled sub-items (Career/Work:) rendered in accent color
  - Footer: www.astrochhayah.com (full card: #AstroChhayah | website | @AstroChhayah)

Font: Nirmala UI (Windows built-in, supports Devanagari + Latin).
Fallback: Arial if Nirmala is unavailable.
"""

import os
import re
import logging
import textwrap
import requests

from datetime import datetime, timezone, timedelta
from io import BytesIO

from PIL import Image, ImageDraw, ImageFont

logger = logging.getLogger(__name__)
logger.info("image_card loaded from: %s", __file__)

# ── Output directory ───────────────────────────────────────────────────────────
OUTPUT_DIR = "cards"

# ── Card dimensions ────────────────────────────────────────────────────────────
CARD_W      = 1080
DATE_H      = 70     # Top strip height for date/weekday
IMAGE_H     = 660    # Spiritual background image height
FOOTER_H    = 140    # Footer strip height (hashtag + website + handle)
LEFT_M      = 55     # Left margin
RIGHT_M     = 55     # Right margin
TEXT_W      = CARD_W - LEFT_M - RIGHT_M   # Usable text width

# ── Font paths (Windows system fonts) ─────────────────────────────────────────
_FONT_PRIMARY  = "C:/Windows/Fonts/Nirmala.ttc"    # Nirmala UI — Devanagari support
_FONT_FALLBACK = "C:/Windows/Fonts/arial.ttf"

# ── Color palette ──────────────────────────────────────────────────────────────
_GOLD        = (212, 175,  55, 255)   # Rich heritage gold  — headings, lines
_SAFFRON     = (230, 138,  40, 255)   # Saffron             — sub-labels, accents
_WHITE       = (252, 248, 240, 255)   # Warm white          — body text
_SILVER      = (185, 180, 210, 255)   # Muted lavender-grey — secondary text
_HASHTAG     = (170, 135,  45, 255)   # Muted gold          — hashtag + website
_DATE_BG     = (  6,   4,  20, 255)   # Near-black indigo   — date strip bg
_PANEL_BG    = ( 12,   8,  38, 255)   # Deep midnight blue  — text panel bg
_FOOTER_BG   = (  8,   5,  25, 255)   # Darker indigo       — footer bg
_LINE        = (212, 175,  55, 160)   # Gold, semi-transparent — decorative lines
_DATE_TEXT   = (220, 200, 130, 255)   # Light gold          — date strip text

# ── Section marker drawn by the renderer (never from post text) ───────────────
_SECTION_MARKER = "◆"

# Known section heading names — detected after emoji stripping
_SECTION_NAMES = {"Meaning:", "Daily Insight:", "Remedy:", "Tip of the Day:"}

# Regex to strip emoji — narrow ranges only, avoids hitting normal Unicode symbols
_EMOJI_RE = re.compile(
    "["
    "\U0001F300-\U0001F5FF"   # symbols & pictographs
    "\U0001F600-\U0001F64F"   # emoticons
    "\U0001F680-\U0001F6FF"   # transport & map
    "\U0001F900-\U0001F9FF"   # supplemental symbols
    "\U0001FA00-\U0001FA6F"   # chess symbols etc.
    "\U0001FA70-\U0001FAFF"   # symbols & pictographs extended-B
    "\U00002702-\U000027B0"   # dingbats (includes ✨ U+2728)
    "]+",
    flags=re.UNICODE,
)

# Regex to detect labeled bullet sub-items: "• Label: rest of text"
# Label is a short word or phrase (with optional /), e.g. "Career/Work", "Kya karein"
_LABEL_RE = re.compile(r"^•\s*([\w/\s]{2,20}):\s*(.+)$")


# ── Font loader ────────────────────────────────────────────────────────────────

def _load_font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    """
    Loads Nirmala UI at the requested size. Falls back to Arial if unavailable.

    Args:
        size (int):  Font point size.
        bold (bool): If True, loads Bold face (index 1 in Nirmala.ttc).

    Returns:
        ImageFont.FreeTypeFont: Always returns a drawable font.
    """
    index = 1 if bold else 0
    if os.path.exists(_FONT_PRIMARY):
        try:
            return ImageFont.truetype(_FONT_PRIMARY, size=size, index=index)
        except Exception as e:
            logger.warning("Nirmala.ttc load error (size=%d bold=%s): %s", size, bold, e)
    if os.path.exists(_FONT_FALLBACK):
        try:
            return ImageFont.truetype(_FONT_FALLBACK, size=size)
        except Exception as e:
            logger.warning("arial.ttf load error (size=%d): %s", size, e)
    return ImageFont.load_default()


# ── Text preprocessing ─────────────────────────────────────────────────────────

def _preprocess(text: str) -> str:
    """
    Prepares raw Telegram post content for image rendering.

    Steps (in order):
    1. Strip all emoji Unicode characters
    2. Strip Telegram markdown markers (* _ `)

    Section detection happens in the renderer using _SECTION_NAMES, not
    via in-text markers, so there is no risk of useful symbols being stripped.

    Args:
        text (str): Raw AI-generated post content (Telegram markdown format).

    Returns:
        str: Clean text safe to render with PIL.
    """
    # Step 1 — strip emojis
    text = _EMOJI_RE.sub("", text)

    # Step 2 — strip Telegram markdown
    text = re.sub(r"\*{3}(.+?)\*{3}", r"\1", text)   # ***bold***
    text = re.sub(r"\*{2}(.+?)\*{2}", r"\1", text)   # **bold**
    text = re.sub(r"\*(.+?)\*",       r"\1", text)   # *bold*
    text = re.sub(r"_(.+?)_",         r"\1", text)   # _italic_
    text = re.sub(r"`(.+?)`",         r"\1", text)   # `code`

    return text


# ── Drawing helpers ────────────────────────────────────────────────────────────

def _shadow(draw: ImageDraw.Draw, xy: tuple, text: str,
             font: ImageFont.FreeTypeFont, color: tuple,
             offset: int = 2) -> None:
    """Draws text with a dark drop shadow for readability over any background."""
    x, y = xy
    draw.text((x + offset, y + offset), text, font=font, fill=(0, 0, 0, 140))
    draw.text((x, y), text, font=font, fill=color)


def _centered(draw: ImageDraw.Draw, text: str, y: int,
               font: ImageFont.FreeTypeFont, color: tuple) -> None:
    """Draws horizontally centered text at the given y position."""
    w = int(font.getlength(text))
    x = (CARD_W - w) // 2
    _shadow(draw, (x, y), text, font, color)


def _gold_line(draw: ImageDraw.Draw, y: int,
                x0: int = LEFT_M, x1: int = CARD_W - RIGHT_M,
                thickness: int = 1) -> None:
    """Draws a thin horizontal gold decorative line."""
    draw.line([(x0, y), (x1, y)], fill=_LINE, width=thickness)


def _wrap_lines(text: str, font: ImageFont.FreeTypeFont, max_w: int) -> list:
    """Returns word-wrapped lines for the given text and pixel width constraint."""
    avg = max(1.0, font.getlength("a"))
    cpl = max(1, int(max_w / avg))
    return textwrap.wrap(text, width=cpl) or [text]


def _render_text(draw, text: str, x: int, y: int,
                  font: ImageFont.FreeTypeFont, color: tuple,
                  max_w: int, indent: int = 0) -> int:
    """
    Renders wrapped text, returning the y position after the final line.
    Pass draw=None for a dry-run height calculation.

    Args:
        draw:    ImageDraw context or None (dry run).
        text:    Single-line text to wrap and render.
        x:       Left x position.
        y:       Starting y position.
        font:    Font for measuring and rendering.
        color:   Text color (RGBA).
        max_w:   Max pixel width before wrapping.
        indent:  Extra left indent for continuation lines (2nd line onwards).

    Returns:
        int: y position after the last rendered line.
    """
    lines  = _wrap_lines(text, font, max_w)
    lh     = int(font.size * 1.45)
    for i, line in enumerate(lines):
        lx = x + (indent if i > 0 else 0)
        if draw is not None:
            _shadow(draw, (lx, y), line, font, color)
        y += lh
    return y


# ── Panchang parser (for date/weekday in date strip) ──────────────────────────

def _parse_panchang(summary: str) -> dict:
    """Parses pipe-delimited panchang summary into a dict."""
    result = {}
    for part in summary.split("|"):
        part = part.strip()
        if ":" in part:
            k, _, v = part.partition(":")
            result[k.strip()] = v.strip()
    return result


# ── Main card generator ────────────────────────────────────────────────────────

def generate_astrology_card(
    image_url: str,
    post_content: str,
    panchang_summary: str = "",
) -> "str | None":
    """
    Creates a full-content portrait image card for the Daily Astrology Bot.

    Layout (top to bottom):
      - Date strip      : Weekday | Date (e.g. "Raviwara  |  April 05, 2026")
      - Spiritual image : Context-matched background from Gemini
      - Content panel   : Full AI-generated panchang post text, auto-height
      - Footer strip    : #AstroChhayah | www.astrochhayah.com | @AstroChhayah

    Args:
        image_url (str):        URL of the Gemini-generated background image.
        post_content (str):     Full AI-generated panchang post (Telegram format).
        panchang_summary (str): Pipe-delimited panchang string (for date strip).

    Returns:
        str:  Absolute path to the saved JPEG file.
        None: If the image download fails or generation errors out.
    """
    if not image_url:
        logger.error("generate_astrology_card: image_url is required.")
        return None

    # ── Download and resize background image ───────────────────────────────────
    try:
        resp = requests.get(image_url, timeout=20)
        resp.raise_for_status()
        bg = Image.open(BytesIO(resp.content)).convert("RGB")
        bg = bg.resize((CARD_W, IMAGE_H), Image.LANCZOS)
    except Exception as e:
        logger.error("generate_astrology_card: background download failed: %s", e)
        return None

    # ── Preprocess content ─────────────────────────────────────────────────────
    clean = _preprocess(post_content)
    content_lines = clean.splitlines()

    # ── Date strip values ──────────────────────────────────────────────────────
    IST = timezone(timedelta(hours=5, minutes=30))
    now = datetime.now(IST)
    date_display = now.strftime("%B %d, %Y")

    fields  = _parse_panchang(panchang_summary) if panchang_summary else {}
    weekday = fields.get("Weekday", fields.get("Vara", now.strftime("%A")))
    date_str = f"{weekday}  |  {date_display}" if weekday else date_display

    # ── Load fonts ─────────────────────────────────────────────────────────────
    f_date     = _load_font(28, bold=False)
    f_header   = _load_font(40, bold=True)    # "Aaj ki Tithi: ..."  (first line)
    f_subtitle = _load_font(30, bold=False)   # "Vishakha Nakshatra • Vajra Yoga"
    f_section  = _load_font(34, bold=True)    # "◆ Meaning:" section headings
    f_label    = _load_font(30, bold=True)    # "Career/Work:" sub-labels
    f_body     = _load_font(30, bold=False)   # Bullet body text
    f_hashtag  = _load_font(26, bold=False)
    f_website  = _load_font(28, bold=True)
    f_handle   = _load_font(28, bold=True)

    line_gap    = 10   # extra space after each logical line
    section_gap = 20   # extra space before a new section heading
    bullet_gap  = 6    # tighter gap between consecutive bullets

    def _is_header(line: str) -> bool:
        return line.startswith("Aaj ki Tithi") or line.startswith("Aaj ka Tithi")

    def _is_subtitle(line: str) -> bool:
        return "Nakshatra" in line and ("•" in line or "Yoga" in line)

    def _is_section(line: str) -> bool:
        # Sections are detected by their text name after emoji/markdown stripping
        return line.strip() in _SECTION_NAMES

    def _is_hashtag(line: str) -> bool:
        return line.strip().startswith("#")

    # ── Render pass (dry run or actual draw) ───────────────────────────────────
    def render(draw_ctx, start_y: int) -> int:
        y = start_y
        prev_was_bullet = False

        for raw in content_lines:
            line = raw.strip()
            if not line:
                y += (bullet_gap if prev_was_bullet else line_gap)
                prev_was_bullet = False
                continue

            if _is_hashtag(line):
                # Skip — hashtags are handled in the footer, not the content area
                prev_was_bullet = False
                continue

            elif _is_header(line):
                y += 8
                y = _render_text(draw_ctx, line, LEFT_M, y, f_header, _GOLD, TEXT_W)
                y += line_gap
                prev_was_bullet = False

            elif _is_subtitle(line):
                y = _render_text(draw_ctx, line, LEFT_M, y, f_subtitle, _SILVER, TEXT_W)
                y += line_gap
                prev_was_bullet = False

            elif _is_section(line):
                y += section_gap
                if draw_ctx:
                    _gold_line(draw_ctx, y)
                y += 12
                # Draw "◆ Heading:" — marker in gold, heading text in saffron
                marker       = _SECTION_MARKER + " "
                heading_text = line.strip()
                if draw_ctx:
                    _shadow(draw_ctx, (LEFT_M, y), marker, f_section, _GOLD)
                    marker_w = int(f_section.getlength(marker))
                    _shadow(draw_ctx, (LEFT_M + marker_w, y), heading_text, f_section, _SAFFRON)
                y += int(f_section.size * 1.45)
                y += line_gap
                prev_was_bullet = False

            elif line.startswith("•"):
                body   = line[1:].strip()
                m      = _LABEL_RE.match(line)
                gap    = bullet_gap if prev_was_bullet else line_gap

                if m:
                    label = m.group(1).strip() + ":"
                    rest  = m.group(2).strip()

                    # Render "  label:" in saffron, then rest as wrapped body text
                    label_str = f"  {label}"
                    label_w   = int(f_label.getlength(label_str))

                    if draw_ctx:
                        _shadow(draw_ctx, (LEFT_M, y), label_str, f_label, _SAFFRON)
                    y += int(f_label.size * 1.45)

                    y = _render_text(draw_ctx, rest, LEFT_M + 18, y, f_body, _WHITE,
                                     TEXT_W - 18)
                    y += gap

                else:
                    # Plain bullet — render "• body" with slight indent on wrap
                    y = _render_text(draw_ctx, line, LEFT_M + 6, y, f_body, _WHITE,
                                     TEXT_W - 6, indent=16)
                    y += gap

                prev_was_bullet = True

            else:
                y = _render_text(draw_ctx, line, LEFT_M, y, f_body, _SILVER, TEXT_W)
                y += line_gap
                prev_was_bullet = False

        return y

    # ── Dry run to get content height ──────────────────────────────────────────
    content_start = DATE_H + IMAGE_H + 30
    content_end   = render(None, content_start)
    card_h        = content_end + FOOTER_H

    # ── Build canvas ───────────────────────────────────────────────────────────
    card = Image.new("RGB", (CARD_W, card_h), _PANEL_BG)

    # Date strip (very dark top bar)
    card.paste(Image.new("RGB", (CARD_W, DATE_H), _DATE_BG), (0, 0))

    # Spiritual image below date strip
    card.paste(bg, (0, DATE_H))

    # Footer strip at bottom
    footer_y = card_h - FOOTER_H
    card.paste(Image.new("RGB", (CARD_W, FOOTER_H), _FOOTER_BG), (0, footer_y))

    # Vignette: smooth gradient from image bottom edge into panel
    vignette = Image.new("RGBA", (CARD_W, IMAGE_H), (0, 0, 0, 0))
    vd = ImageDraw.Draw(vignette)
    for i in range(IMAGE_H):
        alpha = int((i / IMAGE_H) ** 2.2 * 200)
        vd.line([(0, i), (CARD_W, i)], fill=(0, 0, 10, alpha))
    card.paste(vignette, (0, DATE_H), mask=vignette)

    draw = ImageDraw.Draw(card)

    # ── Date strip content ─────────────────────────────────────────────────────
    date_y = (DATE_H - int(f_date.size)) // 2
    _centered(draw, date_str, date_y, f_date, _DATE_TEXT)

    # ── Gold separator between image and content panel ─────────────────────────
    sep_y = DATE_H + IMAGE_H
    draw.line([(0, sep_y), (CARD_W, sep_y)], fill=_GOLD[:3] + (220,), width=3)

    # ── Render all content ─────────────────────────────────────────────────────
    render(draw, content_start)

    # ── Footer ─────────────────────────────────────────────────────────────────
    draw.line([(0, footer_y), (CARD_W, footer_y)], fill=_GOLD[:3] + (180,), width=2)

    # #AstroChhayah — centered
    _centered(draw, "#AstroChhayah", footer_y + 18, f_hashtag, _HASHTAG)

    # Website — centered, slightly larger
    _centered(draw, "www.astrochhayah.com", footer_y + 52, f_website, _GOLD)

    # Separator dot line
    _gold_line(draw, footer_y + 92, x0=LEFT_M, x1=CARD_W - RIGHT_M)

    # @AstroChhayah — right-aligned
    handle_text = "@AstroChhayah"
    handle_x = CARD_W - RIGHT_M - int(f_handle.getlength(handle_text))
    _shadow(draw, (handle_x, footer_y + 104), handle_text, f_handle, _WHITE)

    # ── Save ───────────────────────────────────────────────────────────────────
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    filename    = f"astrology_card_{now.strftime('%Y%m%d')}.jpg"
    output_path = os.path.join(OUTPUT_DIR, filename)
    card.save(output_path, "JPEG", quality=92)
    logger.info("Astrology card saved: %s (%dx%d)", output_path, CARD_W, card_h)
    return os.path.abspath(output_path)


# ── Social card (Instagram / Facebook feed) ────────────────────────────────────

def _extract_section_bullets(post_content: str, section_name: str,
                               max_bullets: int = 2) -> list:
    """
    Extracts the first N bullet lines from a named section of the post content.

    Args:
        post_content (str): Full cleaned post text (markdown stripped).
        section_name (str): e.g. "Meaning:", "Daily Insight:"
        max_bullets (int):  Maximum number of bullet lines to return.

    Returns:
        list[str]: Bullet text strings (without the leading "• ").
    """
    lines   = _preprocess(post_content).splitlines()
    bullets = []
    inside  = False

    for line in lines:
        stripped = line.strip()
        if stripped == section_name:
            inside = True
            continue
        if inside:
            if stripped in _SECTION_NAMES and stripped != section_name:
                break   # hit the next section
            if stripped.startswith("•"):
                bullets.append(stripped[1:].strip())
                if len(bullets) >= max_bullets:
                    break

    return bullets


def generate_social_card(
    image_url: str,
    post_content: str,
    panchang_summary: str = "",
) -> "str | None":
    """
    Creates a fixed 1080x1350 image card optimised for Instagram and Facebook feed posts.

    Instagram and Facebook feed posts display images at a maximum 4:5 ratio (1080x1350).
    Taller images get cropped in the feed preview. This function produces a card that
    fits within that limit by showing curated key content rather than the full post.

    Content shown (in order):
      - Date strip     : Weekday | Date
      - Spiritual image: Context-matched background
      - Tithi + Paksha : Hero text (large, centered)
      - Nakshatra + Yoga
      - ◆ Meaning      : First 2 bullet points
      - ◆ Daily Insight: First 2 bullets
      - ◆ Remedy       : First 2 bullets
      - ◆ Tip of the Day: First 2 bullets
      - Footer         : www.astrochhayah.com (centered)

    Args:
        image_url (str):        URL of the Gemini-generated spiritual background image.
        post_content (str):     Full AI-generated panchang post (Telegram format).
        panchang_summary (str): Pipe-delimited panchang string (for tithi/nakshatra fields).

    Returns:
        str:  Absolute path to the saved JPEG file.
        None: If image download fails or generation errors out.
    """
    # ── Fixed structural dimensions (canvas height is calculated dynamically) ───
    S_DATE_H  = 60
    S_IMAGE_H = 400
    S_FOOT_H  = 70
    S_LEFT    = 55
    S_RIGHT   = 55
    S_TW      = CARD_W - S_LEFT - S_RIGHT   # usable text width

    if not image_url:
        logger.error("generate_social_card: image_url is required.")
        return None

    # ── Download background ────────────────────────────────────────────────────
    try:
        resp = requests.get(image_url, timeout=20)
        resp.raise_for_status()
        bg = Image.open(BytesIO(resp.content)).convert("RGB")
        bg = bg.resize((CARD_W, S_IMAGE_H), Image.LANCZOS)
    except Exception as e:
        logger.error("generate_social_card: background download failed: %s", e)
        return None

    # ── Parse panchang fields ──────────────────────────────────────────────────
    IST     = timezone(timedelta(hours=5, minutes=30))
    now     = datetime.now(IST)
    fields  = _parse_panchang(panchang_summary) if panchang_summary else {}
    weekday = fields.get("Weekday", fields.get("Vara", now.strftime("%A")))
    tithi   = fields.get("Tithi",     "Shubh Tithi")
    paksha  = fields.get("Paksha",    "")
    nk      = fields.get("Nakshatra", "")
    yoga    = fields.get("Yoga",      "")
    date_str = f"{weekday}  |  {now.strftime('%B %d, %Y')}"

    # ── Extract curated bullets from post content ──────────────────────────────
    meaning_bullets  = _extract_section_bullets(post_content, "Meaning:",       2)
    insight_bullets  = _extract_section_bullets(post_content, "Daily Insight:", 2)
    remedy_bullets   = _extract_section_bullets(post_content, "Remedy:",        2)
    tip_bullets      = _extract_section_bullets(post_content, "Tip of the Day:", 2)
    logger.info(
        "generate_social_card: meaning=%d insight=%d remedy=%d tip=%d",
        len(meaning_bullets), len(insight_bullets), len(remedy_bullets), len(tip_bullets),
    )

    # ── Load fonts ─────────────────────────────────────────────────────────────
    f_date    = _load_font(26, bold=False)
    f_tithi   = _load_font(78, bold=True)
    f_paksha  = _load_font(34, bold=False)
    f_sub     = _load_font(28, bold=False)
    f_section = _load_font(26, bold=True)
    f_body    = _load_font(24, bold=False)
    f_website = _load_font(24, bold=True)

    lh_h = int(f_section.size * 1.4)
    lh_b = int(f_body.size    * 1.45)

    sep_y         = S_DATE_H + S_IMAGE_H
    content_start = sep_y + 22

    # ── Render pass ────────────────────────────────────────────────────────────
    # Called twice: first with draw_ctx=None (dry run to measure height),
    # then with the real draw context to actually paint the card.
    def render(draw_ctx, start_y: int) -> int:
        y = start_y

        # Hero: tithi name
        tf = f_tithi if f_tithi.getlength(tithi) < S_TW else _load_font(58, bold=True)
        tw = int(tf.getlength(tithi))
        if draw_ctx:
            _shadow(draw_ctx, ((CARD_W - tw) // 2, y), tithi, tf, _GOLD)
        y += int(tf.size * 1.35)

        # Paksha line
        if paksha:
            pw = int(f_paksha.getlength(paksha))
            if draw_ctx:
                _shadow(draw_ctx, ((CARD_W - pw) // 2, y), paksha, f_paksha, _WHITE)
            y += int(f_paksha.size * 1.4)

        # Nakshatra • Yoga line
        nk_yoga = f"{nk} Nakshatra  •  {yoga} Yoga" if nk and yoga else nk or yoga
        if nk_yoga:
            sw = int(f_sub.getlength(nk_yoga))
            if draw_ctx:
                _shadow(draw_ctx, ((CARD_W - sw) // 2, y), nk_yoga, f_sub, _SILVER)
            y += int(f_sub.size * 1.4)

        def _sec(heading):
            nonlocal y
            y += 10
            if draw_ctx:
                draw_ctx.line([(S_LEFT, y), (CARD_W - S_RIGHT, y)], fill=_LINE, width=1)
            y += 8
            marker = _SECTION_MARKER + " "
            mw     = int(f_section.getlength(marker))
            if draw_ctx:
                _shadow(draw_ctx, (S_LEFT, y), marker, f_section, _GOLD)
                _shadow(draw_ctx, (S_LEFT + mw, y), heading, f_section, _SAFFRON)
            y += lh_h

        def _bullet(text):
            nonlocal y
            # Word-wrap the full bullet text — no truncation
            wrapped = _wrap_lines("• " + text, f_body, S_TW - 10)
            for i, line in enumerate(wrapped):
                lx = S_LEFT + 10 + (16 if i > 0 else 0)   # indent continuation lines
                if draw_ctx:
                    _shadow(draw_ctx, (lx, y), line, f_body, _WHITE)
                y += lh_b

        # Sections
        if meaning_bullets:
            _sec("Meaning:")
            for b in meaning_bullets:
                _bullet(b)

        if insight_bullets:
            _sec("Daily Insight:")
            for b in insight_bullets:
                _bullet(b)

        if remedy_bullets:
            _sec("Remedy:")
            for b in remedy_bullets:
                _bullet(b)

        if tip_bullets:
            _sec("Tip of the Day:")
            for b in tip_bullets:
                _bullet(b)

        return y

    # ── Dry run to measure content height ─────────────────────────────────────
    content_end = render(None, content_start)
    S_CARD_H    = content_end + S_FOOT_H + 20   # 20px bottom padding before footer

    # ── Build canvas ───────────────────────────────────────────────────────────
    card = Image.new("RGB", (CARD_W, S_CARD_H), _PANEL_BG)
    card.paste(Image.new("RGB", (CARD_W, S_DATE_H), _DATE_BG), (0, 0))
    card.paste(bg, (0, S_DATE_H))
    footer_y = S_CARD_H - S_FOOT_H
    card.paste(Image.new("RGB", (CARD_W, S_FOOT_H), _FOOTER_BG), (0, footer_y))

    # Vignette over image bottom
    vig = Image.new("RGBA", (CARD_W, S_IMAGE_H), (0, 0, 0, 0))
    vd  = ImageDraw.Draw(vig)
    for i in range(S_IMAGE_H):
        alpha = int((i / S_IMAGE_H) ** 2.2 * 200)
        vd.line([(0, i), (CARD_W, i)], fill=(0, 0, 10, alpha))
    card.paste(vig, (0, S_DATE_H), mask=vig)

    draw = ImageDraw.Draw(card)

    # Date strip
    dw = int(f_date.getlength(date_str))
    _shadow(draw, ((CARD_W - dw) // 2, (S_DATE_H - int(f_date.size)) // 2),
            date_str, f_date, _DATE_TEXT)

    # Gold separator image→panel
    draw.line([(0, sep_y), (CARD_W, sep_y)], fill=_GOLD[:3] + (220,), width=3)

    # ── Actual render pass ─────────────────────────────────────────────────────
    render(draw, content_start)

    # ── Footer ─────────────────────────────────────────────────────────────────
    draw.line([(0, footer_y), (CARD_W, footer_y)], fill=_GOLD[:3] + (180,), width=2)
    ww = int(f_website.getlength("www.astrochhayah.com"))
    _shadow(draw, ((CARD_W - ww) // 2, footer_y + 18), "www.astrochhayah.com", f_website, _GOLD)

    # ── Save ───────────────────────────────────────────────────────────────────
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    filename    = f"astrology_social_{now.strftime('%Y%m%d')}.jpg"
    output_path = os.path.join(OUTPUT_DIR, filename)
    card.save(output_path, "JPEG", quality=92)
    logger.info("Astrology social card saved: %s (%dx%d)", output_path, CARD_W, S_CARD_H)
    return os.path.abspath(output_path)
